import sys; print('%s %s' % (sys.executable or sys.platform, sys.version))
runfile('/home/sdusunlin/Documents/F/529/code/assign1/validation.py')
import sys; print('%s %s' % (sys.executable or sys.platform, sys.version))
runfile('/home/sdusunlin/Documents/F/529/code/assign1/Assign1/main.py')
runfile('/home/sdusunlin/Documents/F/529/code/assign1/Assign1/validation.py')
import sys; print('%s %s' % (sys.executable or sys.platform, sys.version))
runfile('/home/sdusunlin/Documents/F/529/code/assign1/Assign1/validation.py')
import sys; print('%s %s' % (sys.executable or sys.platform, sys.version))
runfile('/home/sdusunlin/Documents/F/529/code/assign1/Assign1/validation.py')
